
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheus Santana
 */
public class Exerc3 extends javax.swing.JFrame {

    /**
     * Creates new form Exerc3
     */
    public Exerc3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        weightText = new javax.swing.JTextField();
        planetsSelect = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seu Peso em Diferentes Planetas");

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Seu Peso em Diferentes Planetas");

        jLabel2.setText("Peso(kg)");

        planetsSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercúrio", "Vênus", "Marte", "Júpiter", "Saturno", "Urano" }));
        planetsSelect.setToolTipText("Escolha um planeta para poder pesar o seus kilos nele");

        jLabel3.setText("Nome");

        limpar.setText("Limpar");
        limpar.setToolTipText("Limpa os campos digitados");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        calcular.setText("Calcular");
        calcular.setToolTipText("Calcula o seu peso no planeta selecionado");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(planetsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                            .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(weightText)
                                .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(weightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planetsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar)
                    .addComponent(calcular))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        if (nameText.getText().intern() == "") {
            JOptionPane.showMessageDialog(null, 
                    "Digite o seu nome", "Erro", 
                    JOptionPane.WARNING_MESSAGE);
            nameText.requestFocus();
        } else if (weightText.getText().intern() == "") {
            JOptionPane.showMessageDialog(null, 
                    "Digite o seu peso em Kg!!!", "Erro", 
                    JOptionPane.WARNING_MESSAGE);
            weightText.requestFocus();
        } else {
            String name = nameText.getText();
            Float weight =  Float.parseFloat(weightText.getText());
            Float result;
            int planetSelected = planetsSelect.getSelectedIndex();
                if (planetSelected == 0) {
                    result = (weight / 10) * 0.37f;
                    JOptionPane.showMessageDialog(
                            null, name + " o seu peso em " 
                                        + planetsSelect.getSelectedItem() + " é de " + result + "Kg",
                                        "Mercúrio", JOptionPane.INFORMATION_MESSAGE
                    );
                }
                else if (planetSelected == 1) {
                    result = (weight / 10) * 0.88f;
                    JOptionPane.showMessageDialog(
                            null, name + " o seu peso em " 
                                        + planetsSelect.getSelectedItem() + " é de " + result + "Kg",
                                        "Vênus", JOptionPane.INFORMATION_MESSAGE
                    );
                }
                else if (planetSelected == 2) {
                    result = (weight / 10) * 0.38f;
                    JOptionPane.showMessageDialog(
                            null, name + " o seu peso em " 
                                        + planetsSelect.getSelectedItem() + " é de " + result + "Kg",
                                        "Marte", JOptionPane.INFORMATION_MESSAGE
                    );
                }
                else if (planetSelected == 3) {
                    result = (weight / 10) * 2.64f;
                    JOptionPane.showMessageDialog(
                            null, name + " o seu peso em " 
                                        + planetsSelect.getSelectedItem() + " é de " + result + "Kg",
                                        "Júpiter", JOptionPane.INFORMATION_MESSAGE
                    );
                }
                else if (planetSelected == 4) {
                    result = (weight / 10) * 1.15f;
                    JOptionPane.showMessageDialog(
                            null, name + " o seu peso em " 
                                        + planetsSelect.getSelectedItem() + " é de " + result + "Kg",
                                        "Saturno", JOptionPane.INFORMATION_MESSAGE
                    );
                }
                else if (planetSelected == 5) {
                    result = (weight / 10) * 1.17f;
                    JOptionPane.showMessageDialog(
                            null, name + " o seu peso em " 
                                        + planetsSelect.getSelectedItem() + " é de " + result + "Kg",
                                        "Urano", JOptionPane.INFORMATION_MESSAGE
                    );
                }
                
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        nameText.setText(null);
        weightText.setText(null);
        
        nameText.requestFocus();
    }//GEN-LAST:event_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exerc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exerc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exerc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exerc3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exerc3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nameText;
    private javax.swing.JComboBox<String> planetsSelect;
    private javax.swing.JTextField weightText;
    // End of variables declaration//GEN-END:variables
}
